### ISSUE TITLE
Can this project run on mobile devices

### ISSUE THREAD

**Issue by codingwatching** [JuanDiegoMontoya/Gengine#3]
Hi @JuanDiegoMontoya 
Can we build and run Gengine or Voxel_Engine on mobile devices like android and ios?
Thank you so much!

**Comment by JuanDiegoMontoya** [comment]
Currently the project does not support mobile devices, not without relatively significant changes. Theoretically it could work if you compiled all the third party binaries for mobile targets, but then you have to worry about touch support, which is not implemented. I hope that answers your question.

**Comment by codingwatching** [comment]
Hi @JuanDiegoMontoya 
Yes, thank you for the quick reply!
